// After Nitro emits the Vercel prebuilt,inline any bare `import "tslib"` in the
// server bundle by vendoring tslib's ESM source into `_libs/tslib.mjs` and
// rewriting the import specifiers to the relative path. Vercel's prebuilt
// deploy doesn't ship the function's node_modules,so bare tslib imports crash
// every SSR request at module load (ERR_MODULE_NOT_FOUND).

import { readdir, readFile, writeFile, cp } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const funcDir = new URL("../.vercel/output/functions/__server.func/", import.meta.url);
const libsDir = join(funcDir.pathname, "_libs");
const tslibPkgDir = dirname(require.resolve("tslib/package.json"));
const target = join(libsDir, "tslib.mjs");

if (existsSync(libsDir) === false) {
  console.warn("[embed-tslib] no _libs dir;skipping");
  process.exit(0);
}

const esmEntry = join(tslibPkgDir, "tslib.es6.mjs");
if (existsSync(esmEntry)) {
  await cp(tslibPkgDir, join(libsDir, "tslib-pkg"), { recursive: true });
  const shim = [
    `// vendored tslib (auto-generated by scripts/embed-tslib.mjs)`,
    `export * from "./tslib-pkg/tslib.es6.mjs";`,
    `export { default } from "./tslib-pkg/tslib.es6.mjs";`,
    ``,
  ].join("\n");
  await writeFile(target, shim);
} else {
  const cjs = await readFile(join(tslibPkgDir, "tslib.js"), "utf8");
  const helpers = cjs
    .split("\n")
    .filter((l) => /^function (__|tslib|exports|Object\.defineProperty)/.test(l))
    .join("\n");
  const shim = [
    `// vendored tslib (auto-generated by scripts/embed-tslib.mjs; CJS fallback)`,
    `const g = globalThis;`,
    `const exports = {};`,
    helpers,
    `export default exports;`,
    `export const { __assign, __rest, __extends, __spreadArray, __awaiter, __generator, __values, __read, __spread, __decorate, __metadata, __param, __importDefault, __exportStar } = exports;`,
    ``,
  ].join("\n");
  await writeFile(target, shim);
}

for (const name of await readdir(libsDir)) {
  if (!name.endsWith(".mjs")) continue;
  const file = join(libsDir, name);
  const code = await readFile(file, "utf8");
  if (code.includes('from "tslib"') || code.includes("from 'tslib'")) {
    await writeFile(file, code.replace(/from ["']tslib["']/g, `from "./tslib.mjs"`));
    console.log("[embed-tslib] patched", name);
  }
}

console.log("[embed-tslib] vendored tslib at", target);