import { useState } from "react";
import { cn } from "@/lib/utils";

const presets = [{ label: "Navy Mesh", value: "#0B0F19", accent: "#0066FF" }, { label: "Carbon Blue", value: "#07090E", accent: "#00F0FF" }, { label: "Midnight", value: "#050811", accent: "#0066FF" }, { label: "Abyss", value: "#02040A", accent: "#00F0FF" }];

export function BackgroundEditor() {
  const [selected, setSelected] = useState(0);
  const [grid, setGrid] = useState(true);
  const [glow, setGlow] = useState(60);
  const preset = presets[selected];
  return <div className="mx-auto max-w-3xl space-y-8 px-6 py-10"><header><h1 className="text-2xl font-bold text-slate-100">Background Editor</h1><p className="mt-2 text-sm text-slate-400">Customize the immersive workspace backdrop. Changes preview live.</p></header><section className="glass-panel p-6"><h2 className="text-sm font-semibold uppercase tracking-[0.16em] text-slate-500">Base color</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{presets.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={cn("rounded-xl border p-4 text-left transition", selected === index ? "border-cyan-300/40 bg-cyan-300/10" : "border-white/[0.08] hover:border-white/[0.16]")}><span className="block h-10 rounded-lg" style={{ backgroundColor: item.value, boxShadow: `inset 0 0 24px ${item.accent}55` }} /><span className="mt-2 block text-xs font-medium text-slate-300">{item.label}</span></button>)}</div></section><section className="glass-panel p-6"><h2 className="text-sm font-semibold uppercase tracking-[0.16em] text-slate-500">Cybernetic grid</h2><div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-400">Show grid lines</span><button type="button" onClick={() => setGrid(!grid)} className={cn("relative h-6 w-11 rounded-full transition", grid ? "bg-cyan-300/40" : "bg-white/[0.08]")}><span className={cn("absolute top-0.5 h-5 w-5 rounded-full bg-white transition-all", grid ? "left-[22px]" : "left-0.5")} /></button></div></section><section className="glass-panel p-6"><h2 className="text-sm font-semibold uppercase tracking-[0.16em] text-slate-500">Ambient glow intensity</h2><input type="range" min={0} max={100} value={glow} onChange={(event) => setGlow(Number(event.target.value))} className="mt-4 w-full accent-cyan-300" /><p className="mt-2 text-xs text-slate-500">{glow}% intensity</p></section><section className="glass-panel p-6"><h2 className="text-sm font-semibold uppercase tracking-[0.16em] text-slate-500">Preview</h2><div className="mt-4 h-40 rounded-xl border border-white/[0.08]" style={{ backgroundColor: preset.value, backgroundImage: grid ? `linear-gradient(${preset.accent}11 1px, transparent 1px), linear-gradient(90deg, ${preset.accent}11 1px, transparent 1px)` : undefined, backgroundSize: "28px 28px", boxShadow: `inset 0 0 80px ${preset.accent}${Math.round(glow * 2.55).toString(16).padStart(2, "0")}` }} /></section></div>;
}
